# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 知行合一
email: msmsruby@gmail.com
description: 程序员博客，工作以及业余编程中的随笔，做到知行合一。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://msms-nj.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Mans_NJ
github_username:  Msms-NJ
google_analytics: UA-54748333-4

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.html
# - blog.html
